version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/code
    environment:
      - SYNAPSE_HOST
      - SYNAPSE_PORT
      - SYNAPSE_DATABASE
      - SYNAPSE_USER
      - SYNAPSE_PASSWORD

